# This is the configuration file for Azure Pipelines, used to run tests on
# macOS. Documentation to help understand this setup:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/multiple-phases
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index
#
# Self-hosted agents for Windows 10 and Insider Preview are used:
# - 'Hosted Windows Client' is the latest Windows 10
# - 'Hosted Windows Client Next' is 10 Windows Insider Preview
#
# In addition to this configuration file, the "Build pull requests from forks
# of this repository" setting must also be enabled in the Azure DevOps project:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github#validate-contributions-from-forks

trigger: none # disable builds for branches

jobs:
- job: infrastructure_win10
  displayName: 'infrastructure/ tests (Windows 10)'
  #dependsOn: root
  #condition: dependencies.root.outputs['test_jobs.wptrunner_infrastructure']
  pool:
    name: 'Hosted Windows Client Next'
  steps:
  - template: tools/ci/azure/system_info.yml
  - template: tools/ci/azure/checkout.yml
  - template: tools/ci/azure/install_python.yml
  - template: tools/ci/azure/pip_install.yml
    parameters:
      packages: virtualenv
  - template: tools/ci/azure/install_certs.yml
  #- template: tools/ci/azure/install_chrome.yml
  - template: tools/ci/azure/update_hosts.yml
  #- template: tools/ci/azure/update_manifest.yml
  - script: python ./wpt run --yes --install-fonts --metadata infrastructure/metadata/ --log-tbpl $(Build.ArtifactStagingDirectory)/edge.tbpl.log --log-tbpl-level info edge_webdriver infrastructure/
    displayName: 'Run tests (Edge)'
    continueOnError: true
  - script: python ./wpt run --yes --install-browser --install-fonts --metadata infrastructure/metadata/ --log-tbpl $(Build.ArtifactStagingDirectory)/firefox.tbpl.log --log-tbpl-level info --channel nightly firefox infrastructure/
    displayName: 'Run tests (Firefox)'
    continueOnError: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish results'
    inputs:
      artifactName: 'results'
    condition: succeededOrFailed()
  - powershell: |
      $hostFile = "$env:systemroot\System32\drivers\etc\hosts"
      Copy-Item -Path "$hostFile.back" -Destination $hostFile -Force
    displayName: 'Restore hosts file and cleanup test machine'
    condition: always()
    continueOnError: true
    errorActionPreference: silentlyContinue
